services:
  api:
    build: .
    entrypoint: ["sh", "-c", "poetry run alembic upgrade head && poetry run python ./app/main.py"]
    container_name: fastapi_container
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG:-False}
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  worker:
    build: .
    command: poetry run celery -A app.celery_worker.app worker --loglevel=info
    container_name: celery_worker
    restart: unless-stopped
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG:-False}
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

volumes:
  pgdata:
  redisdata: